// clients/react/src/components/common/incident-tile-box/incident-tile-box.tsx
import "./incident.tile.box.scss";

function IncidentTileBox() {

  return (
    <>
      <a className="text-decoration-none">
        <div className="card shadow text-center">
          <div className="card-body d-flex align-items-center justify-content-center">
            <div className="color-box rounded bg-danger"></div>
          </div>
          <div className="card-footer">hola mundo</div>
        </div>
      </a>
    </>
  );
}

export default IncidentTileBox;

// src/app/shared/components/incident-tile-box/incident-tile-box.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Incident } from '@core/models/incident';

@Component({
  selector: 'ta9-incident-tile-box',
  templateUrl: './incident-tile-box.component.html',
  styleUrls: ['./incident-tile-box.component.scss']
})
export class IncidentTileBoxComponent {

  @Input() incident!: Incident;

  @Input() basePath?: string;

  constructor() { }
}

<div class="card shadow text-center">
  <div class="card-body d-flex align-items-center justify-content-center">
    <div
      class="color-box rounded"
      [style.background-color]="incident.color"
    ></div>
  </div>
  <div class="card-footer">
    {{ incident.name }}
  </div>
</div>
