// clients/vue/src/components/common/IncidentCard.vue
<script setup lang="ts">
import { Incident } from '@/interfaces/incident';

interface IncidentsCardProps {
  incident: Incident;
  basePath: string;
}

const props = withDefaults(defineProps<IncidentsCardProps>(), {
  basePath: '',
});
</script>

<template>
  <a
    :href="`/${props.basePath}/${props.incident.id}`"
    class="text-decoration-none link"
  >
    <div class="col-1">
      <div class="color-box rounded"></div>
    </div>
    <div class="col-3 name">{{ props.incident.name }}</div>
    <div class="col">{{ props.incident.createdAt }}</div>
    <div class="col">{{ props.incident.updatedAt }}</div>
    <div class="col">{{ props.incident.createdBy }}</div>
  </a>
</template>

<style scoped lang="scss">
:host {
  display: block;
}

.link {
  display: flex;
  height: 4.438rem;
  background-color: #fff;
  padding: 1rem;
  color: #797979;
  align-items: center;

  &:hover {
    border: 0.06rem solid #077df9 !important;
    .name {
      color: #077df9;
    }
  }
}

.color-box {
  width: 1.5rem;
  height: 1.5rem;
}
</style>

// src/app/shared/components/incident-card/incident-card.component.ts
import { ChangeDetectionStrategy, Component, Input, OnInit } from '@angular/core';
import { Incident } from '@core/models/incident';

@Component({
  selector: 'ta9-incident-card',
  templateUrl: './incident-card.component.html',
  styleUrls: ['./incident-card.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IncidentCardComponent {

  @Input() incident!: Incident;

  @Input() basePath: string;

  dateFormatForPipe: string;

  constructor() { 
    this.dateFormatForPipe = 'dd/MM/yyy';
    this.basePath = '';
  }
}

<a
  routerLink="/{{ baseUrl }}/{{ incident.id }}"
  class="text-decoration-none link"
  href=""
>
  <div class="col-1">
    <div
      class="color-box rounded"
      [style.background-color]="incident.color"
    ></div>
  </div>
  <div class="col-3 name">{{ incident.name }}</div>
  <div class="col">{{ incident.createdAt | date: dateFormatForPipe }}</div>
  <div class="col">{{ incident.updatedAt | date: dateFormatForPipe }}</div>
  <div class="col">{{ incident.createdBy }}</div>
</a>
